### ISSUE TITLE
Status Update - Peyton Fraser

### ISSUE THREAD

**Issue by peytonfraser** [microsoft/iot-cardboard-js#883]
**Done: (2/21/2023)**
- [x] Met with Eslam on Bing AIQ metrics to leverage for AIQ spec
- [x] Provided commentary on AKS feedback design from Haiyuan
- [x] Created initial draft/skeleton of the AI Quality spec

**To-Do:**
- [ ] Parse the model scenarios (classification, recognition, identification, etc.) and metric definitions for the AI Quality spec
